---
title: "Lab 04 - La Quinta is Spanish for next to Denny's, Pt. 2"
author: "Jonathan Klus"
date: "21 September 2021"
output: github_document
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse)
library(dsbox)
```

```{r load-data, message = FALSE}
states = read_csv("data/states.csv")
```

### Exercise 0

```{r lintr-warm-up}

str_c("Here is an incredible, grandiloquent,", 
      "extreme, terrible, verbose, lengthy, awesome-in-the-original-sense,", 
      "no good and very long line (of code).")

better_variable_name = 0
this_is_a_bad_boolean = TRUE
needs_infix_spacing = 1 * 0^0
this = mtcars %>% 
  mutate(needs = mpg * wt) %>% 
  mutate(to_have = hp / cyl) %>%
  mutate(one = "pipe_step") %>% 
  mutate(per = "line")
```

### Exercise 1

```{r}
lint_assignment()
```


### Exercise 2

```{r}
dn_ak = dennys %>%
  dplyr::filter(state == "AK")
```

There are `r nrow(dn_ak)` Dennys locations in Alaska. 

### Exercise 3

...

### Exercise 4

...


### Exercise 5


### Exercise 6

```{r load-haversine}
source("haversine.R")
```

...Add additional chunks and description for Ex 6 as needed.

...

Add more exercise headings, chunks, etc, as needed.
